### ISSUE TITLE
Names missing from probability list of overlapping streamers

### ISSUE THREAD

**Issue by Bomjus1** [snoww/TwitchOverlapAPI#1]
Maybe this isn't a bug, so this might just be a question on my part, but why are some streamer's names missing from the list of overlapped streamers? is it because there isn't enough overlap for them to warrant being on the list below the graph?

for example, Hirona has ~400 overlapping chatters to RatedEpicz channel at one point according to this graph: 
![image](https://user-images.githubusercontent.com/39278089/116400187-5f21b900-a7ef-11eb-9e2f-2dce26a57a1c.png)

yet, Hirona is not listed in the probability list below, at any percent. why is this? is the list below the graph, probability based on chatting trends over the past month or something? so a single day isn't enough to matter?

a 2nd example is Hasan overlapping with moonmoon. There's 1600 overlapping chatters, but Hasanabi is not listed in the probability list. 
![image](https://user-images.githubusercontent.com/39278089/116400199-634dd680-a7ef-11eb-986d-543776a3f573.png)

this site is awesome, i'm just trying to better understand the data in front of me. 

oh and 2nd question, what timezone are the graphs using? is it my local timezone or a set one?

**Comment by snoww** [comment]
Hey, thanks for the question. 
The graph shows the last 24 overlap points of data, it graphs the top 6 overlap channels. The data table below only shows the latest overlap data, however it shows all the overlapped channels. 
There might be plans in the future, where I include the data table for past overlap of data as well.
The timezone is in UTC.

**Comment by Bomjus1** [comment]
Thanks for the clarification! Sorry if you explained this and I just didn't understand, but if the "data table below....shows all the overlapped channels" how come moonmoon was not listed as an overlapped channel in the table below on ramee and ratedepicz's pages? the graph indicated overlap from moon's channel to ramee's/rated's channel, but his name was/is not in the table below.

**Comment by snoww** [comment]
No worries, it’s because the table only shows the last updates’ overlaps. So if moonmoon went offline in the latest update, it won’t be on the table. Maybe I’m not explaining it the best.

**Comment by Bomjus1** [comment]
No that makes more sense, sorry for the confusion on my part. Thanks again for the help and the site! You can close/delete this as you see fit.
