### ISSUE TITLE
Similarity over time for channel pages

### ISSUE THREAD

**Issue by ctlaltdefeat** [snoww/TwitchOverlapAPI#2]
It'd be nice to be able to view the ranking of similar channels over time (say, the same period as the Atlas) from within the channel page/view.

**Comment by snoww** [comment]
I think this is a pretty good idea. I'll have to see how I can implement this.

Maybe something along the lines a tab for: now, daily, weekly, monthly
Maybe also show the change in ranking on the left side.

**Comment by ctlaltdefeat** [comment]
seems to have been implemented
